name: Main

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: zip -r extension.zip ~/* -x "*.DS_Store" -x "*.git*"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: extension.zip
